### ISSUE TITLE
Timeout causes unhandled exception to be thrown

### ISSUE THREAD

**Issue by phawxby** [joaolrpaulo/winston-newrelic-logs-transport#13]
https://github.com/joaolrpaulo/winston-newrelic-logs-transport/blob/d1ff186ce42c0deae390c9163da8b194dd6e18bc/index.ts#L29-L33

As the call to NewRelic is an async operation that is not awaited or handled in a callback if the request times out then an unhandled error is thrown. It would also be good if it were possible to increase the timeout or supply additional options.

**Comment by joaolrpaulo** [comment]
Hello @phawxby, are you able to create a Pull Request for this improvement? 🙏🏼

**Comment by phawxby** [comment]
> Hello @phawxby, are you able to create a Pull Request for this improvement? 🙏🏼

I'll quickly throw something together now. I'm having to do some research because [as noted here](https://github.com/winstonjs/winston-transport/issues/33) it's a secret how the callback is supposed to be used. So I'm basically going to [copy this](https://github.com/winstonjs/winston-mongodb/blob/master/lib/winston-mongodb.js#L229-L235).

**Comment by joaolrpaulo** [comment]
Version 1.1.0 published

**Comment by phawxby** [comment]
Thanks!
