### ISSUE TITLE
Seems to use old/wrong header

### ISSUE THREAD

**Issue by phawxby** [joaolrpaulo/winston-newrelic-logs-transport#17]
https://github.com/joaolrpaulo/winston-newrelic-logs-transport/blob/79b2294e9ad2e3fbfd9b9dd0ef2224b58b56fbfb/index.ts#L20

I was implementing a batching function this morning and found this, it seems we're using an undocumented header. I can't find any reference to `X-License-Key`
https://docs.newrelic.com/docs/logs/log-api/introduction-log-api/#auth-header

**Comment by joaolrpaulo** [comment]
Cleanup PR will be added before next version is published. Already mitigated in #18.

**Comment by joaolrpaulo** [comment]
Fixed by #18.
